// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"net/url"

	"github.com/go-openapi/runtime"
	rtclient "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/heww/xk6-harbor/pkg/harbor/client/artifact"
	"github.com/heww/xk6-harbor/pkg/harbor/client/auditlog"
	"github.com/heww/xk6-harbor/pkg/harbor/client/configure"
	"github.com/heww/xk6-harbor/pkg/harbor/client/gc"
	"github.com/heww/xk6-harbor/pkg/harbor/client/icon"
	"github.com/heww/xk6-harbor/pkg/harbor/client/immutable"
	"github.com/heww/xk6-harbor/pkg/harbor/client/ldap"
	"github.com/heww/xk6-harbor/pkg/harbor/client/member"
	"github.com/heww/xk6-harbor/pkg/harbor/client/oidc"
	"github.com/heww/xk6-harbor/pkg/harbor/client/ping"
	"github.com/heww/xk6-harbor/pkg/harbor/client/preheat"
	"github.com/heww/xk6-harbor/pkg/harbor/client/project"
	"github.com/heww/xk6-harbor/pkg/harbor/client/quota"
	"github.com/heww/xk6-harbor/pkg/harbor/client/registry"
	"github.com/heww/xk6-harbor/pkg/harbor/client/replication"
	"github.com/heww/xk6-harbor/pkg/harbor/client/repository"
	"github.com/heww/xk6-harbor/pkg/harbor/client/retention"
	"github.com/heww/xk6-harbor/pkg/harbor/client/robot"
	"github.com/heww/xk6-harbor/pkg/harbor/client/robotv1"
	"github.com/heww/xk6-harbor/pkg/harbor/client/scan"
	"github.com/heww/xk6-harbor/pkg/harbor/client/scan_all"
	"github.com/heww/xk6-harbor/pkg/harbor/client/scanner"
	"github.com/heww/xk6-harbor/pkg/harbor/client/search"
	"github.com/heww/xk6-harbor/pkg/harbor/client/system_cve_allowlist"
	"github.com/heww/xk6-harbor/pkg/harbor/client/systeminfo"
	"github.com/heww/xk6-harbor/pkg/harbor/client/user"
	"github.com/heww/xk6-harbor/pkg/harbor/client/usergroup"
	"github.com/heww/xk6-harbor/pkg/harbor/client/webhook"
	"github.com/heww/xk6-harbor/pkg/harbor/client/webhookjob"
)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v2.0"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

type Config struct {
	// URL is the base URL of the upstream server
	URL *url.URL
	// Transport is an inner transport for the client
	Transport http.RoundTripper
	// AuthInfo is for authentication
	AuthInfo runtime.ClientAuthInfoWriter
}

// New creates a new harbor API HTTP client.
func New(c Config) *HarborAPI {
	var (
		host     = DefaultHost
		basePath = DefaultBasePath
		schemes  = DefaultSchemes
	)

	if c.URL != nil {
		host = c.URL.Host
		basePath = c.URL.Path
		schemes = []string{c.URL.Scheme}
	}

	transport := rtclient.New(host, basePath, schemes)
	if c.Transport != nil {
		transport.Transport = c.Transport
	}

	cli := new(HarborAPI)
	cli.Transport = transport
	cli.Artifact = artifact.New(transport, strfmt.Default, c.AuthInfo)
	cli.Auditlog = auditlog.New(transport, strfmt.Default, c.AuthInfo)
	cli.Configure = configure.New(transport, strfmt.Default, c.AuthInfo)
	cli.GC = gc.New(transport, strfmt.Default, c.AuthInfo)
	cli.Icon = icon.New(transport, strfmt.Default, c.AuthInfo)
	cli.Immutable = immutable.New(transport, strfmt.Default, c.AuthInfo)
	cli.Ldap = ldap.New(transport, strfmt.Default, c.AuthInfo)
	cli.Member = member.New(transport, strfmt.Default, c.AuthInfo)
	cli.OIDC = oidc.New(transport, strfmt.Default, c.AuthInfo)
	cli.Ping = ping.New(transport, strfmt.Default, c.AuthInfo)
	cli.Preheat = preheat.New(transport, strfmt.Default, c.AuthInfo)
	cli.Project = project.New(transport, strfmt.Default, c.AuthInfo)
	cli.Quota = quota.New(transport, strfmt.Default, c.AuthInfo)
	cli.Registry = registry.New(transport, strfmt.Default, c.AuthInfo)
	cli.Replication = replication.New(transport, strfmt.Default, c.AuthInfo)
	cli.Repository = repository.New(transport, strfmt.Default, c.AuthInfo)
	cli.Retention = retention.New(transport, strfmt.Default, c.AuthInfo)
	cli.Robot = robot.New(transport, strfmt.Default, c.AuthInfo)
	cli.Robotv1 = robotv1.New(transport, strfmt.Default, c.AuthInfo)
	cli.Scan = scan.New(transport, strfmt.Default, c.AuthInfo)
	cli.ScanAll = scan_all.New(transport, strfmt.Default, c.AuthInfo)
	cli.Scanner = scanner.New(transport, strfmt.Default, c.AuthInfo)
	cli.Search = search.New(transport, strfmt.Default, c.AuthInfo)
	cli.SystemCVEAllowlist = system_cve_allowlist.New(transport, strfmt.Default, c.AuthInfo)
	cli.Systeminfo = systeminfo.New(transport, strfmt.Default, c.AuthInfo)
	cli.User = user.New(transport, strfmt.Default, c.AuthInfo)
	cli.Usergroup = usergroup.New(transport, strfmt.Default, c.AuthInfo)
	cli.Webhook = webhook.New(transport, strfmt.Default, c.AuthInfo)
	cli.Webhookjob = webhookjob.New(transport, strfmt.Default, c.AuthInfo)
	return cli
}

// HarborAPI is a client for harbor API
type HarborAPI struct {
	Artifact           *artifact.Client
	Auditlog           *auditlog.Client
	Configure          *configure.Client
	GC                 *gc.Client
	Icon               *icon.Client
	Immutable          *immutable.Client
	Ldap               *ldap.Client
	Member             *member.Client
	OIDC               *oidc.Client
	Ping               *ping.Client
	Preheat            *preheat.Client
	Project            *project.Client
	Quota              *quota.Client
	Registry           *registry.Client
	Replication        *replication.Client
	Repository         *repository.Client
	Retention          *retention.Client
	Robot              *robot.Client
	Robotv1            *robotv1.Client
	Scan               *scan.Client
	ScanAll            *scan_all.Client
	Scanner            *scanner.Client
	Search             *search.Client
	SystemCVEAllowlist *system_cve_allowlist.Client
	Systeminfo         *systeminfo.Client
	User               *user.Client
	Usergroup          *usergroup.Client
	Webhook            *webhook.Client
	Webhookjob         *webhookjob.Client
	Transport          runtime.ClientTransport
}
