// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Metadata metadata
//
// swagger:model Metadata
type Metadata struct {

	// icon
	Icon string `json:"icon,omitempty" js:"icon"`

	// id
	ID string `json:"id,omitempty" js:"id"`

	// maintainers
	Maintainers []string `json:"maintainers" js:"maintainers"`

	// name
	Name string `json:"name,omitempty" js:"name"`

	// source
	Source string `json:"source,omitempty" js:"source"`

	// version
	Version string `json:"version,omitempty" js:"version"`
}

// Validate validates this metadata
func (m *Metadata) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metadata based on context it is used
func (m *Metadata) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Metadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Metadata) UnmarshalBinary(b []byte) error {
	var res Metadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
