// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RetentionSelector retention selector
//
// swagger:model RetentionSelector
type RetentionSelector struct {

	// decoration
	Decoration string `json:"decoration,omitempty" js:"decoration"`

	// extras
	Extras string `json:"extras,omitempty" js:"extras"`

	// kind
	Kind string `json:"kind,omitempty" js:"kind"`

	// pattern
	Pattern string `json:"pattern,omitempty" js:"pattern"`
}

// Validate validates this retention selector
func (m *RetentionSelector) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this retention selector based on context it is used
func (m *RetentionSelector) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RetentionSelector) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetentionSelector) UnmarshalBinary(b []byte) error {
	var res RetentionSelector
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
