// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RetentionExecutionTask retention execution task
//
// swagger:model RetentionExecutionTask
type RetentionExecutionTask struct {

	// end time
	EndTime string `json:"end_time,omitempty" js:"endTime"`

	// execution id
	ExecutionID int64 `json:"execution_id,omitempty" js:"executionID"`

	// id
	ID int64 `json:"id,omitempty" js:"id"`

	// job id
	JobID string `json:"job_id,omitempty" js:"jobID"`

	// repository
	Repository string `json:"repository,omitempty" js:"repository"`

	// retained
	Retained int64 `json:"retained" js:"retained"`

	// start time
	StartTime string `json:"start_time,omitempty" js:"startTime"`

	// status
	Status string `json:"status,omitempty" js:"status"`

	// status code
	StatusCode int64 `json:"status_code" js:"statusCode"`

	// status revision
	StatusRevision int64 `json:"status_revision,omitempty" js:"statusRevision"`

	// total
	Total int64 `json:"total" js:"total"`
}

// Validate validates this retention execution task
func (m *RetentionExecutionTask) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this retention execution task based on context it is used
func (m *RetentionExecutionTask) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RetentionExecutionTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RetentionExecutionTask) UnmarshalBinary(b []byte) error {
	var res RetentionExecutionTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
