// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserCreationReq user creation req
//
// swagger:model UserCreationReq
type UserCreationReq struct {

	// comment
	Comment string `json:"comment,omitempty" js:"comment"`

	// email
	Email string `json:"email,omitempty" js:"email"`

	// password
	Password string `json:"password,omitempty" js:"password"`

	// realname
	Realname string `json:"realname,omitempty" js:"realname"`

	// username
	Username string `json:"username,omitempty" js:"username"`
}

// Validate validates this user creation req
func (m *UserCreationReq) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this user creation req based on context it is used
func (m *UserCreationReq) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserCreationReq) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserCreationReq) UnmarshalBinary(b []byte) error {
	var res UserCreationReq
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
