// Code generated by go-swagger; DO NOT EDIT.

package configure

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery --name API --keeptree --with-expecter --case underscore

// API is the interface of the configure client
type API interface {
	/*
	   GetConfigurations gets system configurations

	   This endpoint is for retrieving system configurations that only provides for admin user.
	*/
	GetConfigurations(ctx context.Context, params *GetConfigurationsParams) (*GetConfigurationsOK, error)
	/*
	   GetInternalconfig gets internal configurations

	   This endpoint is for retrieving system configurations that only provides for internal api call.
	*/
	GetInternalconfig(ctx context.Context, params *GetInternalconfigParams) (*GetInternalconfigOK, error)
	/*
	   UpdateConfigurations modifies system configurations

	   This endpoint is for modifying system configurations that only provides for admin user.
	*/
	UpdateConfigurations(ctx context.Context, params *UpdateConfigurationsParams) (*UpdateConfigurationsOK, error)
}

// New creates a new configure API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for configure API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetConfigurations gets system configurations

This endpoint is for retrieving system configurations that only provides for admin user.
*/
func (a *Client) GetConfigurations(ctx context.Context, params *GetConfigurationsParams) (*GetConfigurationsOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getConfigurations",
		Method:             "GET",
		PathPattern:        "/configurations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetConfigurationsReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	switch value := result.(type) {
	case *GetConfigurationsOK:
		return value, nil
	case *GetConfigurationsUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetConfigurationsForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetConfigurationsInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getConfigurations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
GetInternalconfig gets internal configurations

This endpoint is for retrieving system configurations that only provides for internal api call.
*/
func (a *Client) GetInternalconfig(ctx context.Context, params *GetInternalconfigParams) (*GetInternalconfigOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getInternalconfig",
		Method:             "GET",
		PathPattern:        "/internalconfig",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetInternalconfigReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	switch value := result.(type) {
	case *GetInternalconfigOK:
		return value, nil
	case *GetInternalconfigUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetInternalconfigForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetInternalconfigInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getInternalconfig: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateConfigurations modifies system configurations

This endpoint is for modifying system configurations that only provides for admin user.
*/
func (a *Client) UpdateConfigurations(ctx context.Context, params *UpdateConfigurationsParams) (*UpdateConfigurationsOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateConfigurations",
		Method:             "PUT",
		PathPattern:        "/configurations",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdateConfigurationsReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	switch value := result.(type) {
	case *UpdateConfigurationsOK:
		return value, nil
	case *UpdateConfigurationsUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateConfigurationsForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateConfigurationsInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateConfigurations: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}
