// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

//go:generate mockery --name API --keeptree --with-expecter --case underscore

// API is the interface of the quota client
type API interface {
	/*
	   GetQuota gets the specified quota

	   Get the specified quota*/
	GetQuota(ctx context.Context, params *GetQuotaParams) (*GetQuotaOK, error)
	/*
	   ListQuotas lists quotas

	   List quotas*/
	ListQuotas(ctx context.Context, params *ListQuotasParams) (*ListQuotasOK, error)
	/*
	   UpdateQuota updates the specified quota

	   Update hard limits of the specified quota*/
	UpdateQuota(ctx context.Context, params *UpdateQuotaParams) (*UpdateQuotaOK, error)
}

// New creates a new quota API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry, authInfo runtime.ClientAuthInfoWriter) *Client {
	return &Client{
		transport: transport,
		formats:   formats,
		authInfo:  authInfo,
	}
}

/*
Client for quota API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
	authInfo  runtime.ClientAuthInfoWriter
}

/*
GetQuota gets the specified quota

Get the specified quota
*/
func (a *Client) GetQuota(ctx context.Context, params *GetQuotaParams) (*GetQuotaOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getQuota",
		Method:             "GET",
		PathPattern:        "/quotas/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetQuotaReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	switch value := result.(type) {
	case *GetQuotaOK:
		return value, nil
	case *GetQuotaUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetQuotaForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetQuotaNotFound:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *GetQuotaInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getQuota: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
ListQuotas lists quotas

List quotas
*/
func (a *Client) ListQuotas(ctx context.Context, params *ListQuotasParams) (*ListQuotasOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listQuotas",
		Method:             "GET",
		PathPattern:        "/quotas",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListQuotasReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	switch value := result.(type) {
	case *ListQuotasOK:
		return value, nil
	case *ListQuotasUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *ListQuotasForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *ListQuotasInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listQuotas: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
UpdateQuota updates the specified quota

Update hard limits of the specified quota
*/
func (a *Client) UpdateQuota(ctx context.Context, params *UpdateQuotaParams) (*UpdateQuotaOK, error) {

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "updateQuota",
		Method:             "PUT",
		PathPattern:        "/quotas/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UpdateQuotaReader{formats: a.formats},
		AuthInfo:           a.authInfo,
		Context:            ctx,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	switch value := result.(type) {
	case *UpdateQuotaOK:
		return value, nil
	case *UpdateQuotaBadRequest:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateQuotaUnauthorized:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateQuotaForbidden:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateQuotaNotFound:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	case *UpdateQuotaInternalServerError:
		return nil, runtime.NewAPIError("unsuccessful response", value, value.Code())
	}
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for updateQuota: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}
